# Analyse factorielle des correspondances

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
donnee = pd.read_excel("donnee.xlsx")
print(donnee)

  yeux/cheveux  Chatains  Roux  Blonds
0      Marrons       119    26       7
1     Noisette        54    14      10
2        Verts        29    14      16
3        Bleus        84    17      94


In [3]:
data = np.array(donnee)

In [4]:
N = data[:,1:]
N = N.astype(float)


In [5]:
F = N/484
F 

array([[0.24586777, 0.05371901, 0.01446281],
       [0.11157025, 0.02892562, 0.02066116],
       [0.05991736, 0.02892562, 0.03305785],
       [0.17355372, 0.03512397, 0.19421488]])

In [6]:
F_K_plus =F.sum(axis=1)
F_plus_L =F.sum(axis=0)
print(F_K_plus)
print(np.transpose(F_plus_L))

[0.31404959 0.16115702 0.12190083 0.40289256]
[0.59090909 0.14669421 0.26239669]


In [7]:
F_K_plus =F_K_plus.reshape(4,1)
F_plus_L = F_plus_L.reshape(3,1)

In [8]:
F_approx =np.dot(F_K_plus,F_plus_L.T)
F_approx

array([[0.18557476, 0.04606926, 0.08240557],
       [0.09522915, 0.0236408 , 0.04228707],
       [0.07203231, 0.01788215, 0.03198637],
       [0.23807288, 0.05910201, 0.10571768]])

In [9]:
F_error = np.square(F-F_approx)/F_approx

In [10]:
X_carre = 484*F_error.sum()
X_carre

97.82186044949357

#### Etant donne que la valeur statistique de test est superieur au quantile d'ordre 1-α de la loi de Khi-deux a (K-1)(L-1) degre de liberte  alors l'hypothese H0 d'independance des variables est rejeter 
## On peut donc commencer l'AFC

#### AFC = ACP ligne + ACP colonne

In [11]:
D_K_point = np.diag(F_K_plus.reshape(4,))
D_K_point

array([[0.31404959, 0.        , 0.        , 0.        ],
       [0.        , 0.16115702, 0.        , 0.        ],
       [0.        , 0.        , 0.12190083, 0.        ],
       [0.        , 0.        , 0.        , 0.40289256]])

In [12]:
D_point_l = np.diag(F_plus_L.reshape(3,))
D_point_l

array([[0.59090909, 0.        , 0.        ],
       [0.        , 0.14669421, 0.        ],
       [0.        , 0.        , 0.26239669]])

In [13]:
inv_D_K_point = np.linalg.inv(D_K_point)
inv_D_point_l = np.linalg.inv(D_point_l)

In [14]:
L = np.dot(inv_D_K_point,F)
C = np.dot(inv_D_point_l,np.transpose(F))

In [15]:
Lc = L - np.ones((4,1)).dot(np.transpose(F_plus_L))

In [16]:
S_carre = Lc.transpose().dot(np.dot(inv_D_K_point,Lc))

In [17]:
S_carre_M = np.dot(S_carre,inv_D_point_l)

#### Il faut maintenant trouver les vecteur propres de la matrice de S_carre_M

In [ ]:
val_propres, vec_propres = np.linalg.eig(S_carre_M)

In [ ]:
indices = np.argsort(val_propres)[::-1]
vec_propres = vec_propres[:,indices]
val_propres = val_propres[indices]

# Projection des données sur les vecteurs propres
D_proj = np.dot(D_centre, vec_propres)

# Visualisation des deux premières composantes principales
plt.figure(figsize=(6, 4))
plt.scatter(D_proj[:, 0], D_proj[:, 1])
plt.xlabel('Première composante principale')
plt.ylabel('Deuxième composante principale')
plt.show()