In [33]:
import pandas as pd
from fanalysis.ca import CA
import numpy as np
import matplotlib.pyplot as plt
import acp_functions as acp_functions

In [34]:
df = pd.read_excel("donnee.xlsx")
df

yeux  Chatains  Roux  Blonds
0   Marrons       119    26       7
1  Noisette        54    14      10
2     Verts        29    14      16
3     Bleus        84    17      94

In [35]:
hair_colors = list(df.columns)[1:]
eye_colors = df['yeux']

In [36]:
X = df[hair_colors].values

In [37]:
#calcul du profil ligne
row_sum = np.sum(X, axis=1)
column_sum=np.sum(X,axis=0)
row_profile = X/row_sum[:,np.newaxis]
columns_profile=X/column_sum

print(row_sum)
#affichage
print("profil ligne: ")
print(pd.DataFrame(row_profile, index=eye_colors, columns=hair_colors))
print("profil colonne: ")
print(pd.DataFrame(columns_profile, index=eye_colors, columns=hair_colors))

[152  78  59 195]
profil ligne: 
          Chatains      Roux    Blonds
yeux                                  
Marrons   0.782895  0.171053  0.046053
Noisette  0.692308  0.179487  0.128205
Verts     0.491525  0.237288  0.271186
Bleus     0.430769  0.087179  0.482051
profil colonne: 
          Chatains      Roux    Blonds
yeux                                  
Marrons   0.416084  0.366197  0.055118
Noisette  0.188811  0.197183  0.078740
Verts     0.101399  0.197183  0.125984
Bleus     0.293706  0.239437  0.740157


In [38]:
rows_sum_frequences=row_sum/np.sum(X)
columns_sum_frequences=column_sum/np.sum(X)

In [39]:
DK=np.diag(rows_sum_frequences)
DL=np.diag(columns_sum_frequences)
#Déterminons la matrice F

F=X/np.sum(X)

print("Dk", DK)
print("DL", DL)
print("F", F)


Dk [[0.31404959 0.         0.         0.        ]
 [0.         0.16115702 0.         0.        ]
 [0.         0.         0.12190083 0.        ]
 [0.         0.         0.         0.40289256]]
DL [[0.59090909 0.         0.        ]
 [0.         0.14669421 0.        ]
 [0.         0.         0.26239669]]
F [[0.24586777 0.05371901 0.01446281]
 [0.11157025 0.02892562 0.02066116]
 [0.05991736 0.02892562 0.03305785]
 [0.17355372 0.03512397 0.19421488]]


In [40]:
#calcul de la matrice L_barre
L_barre = np.sum(F, axis=0)
C_barre = np.sum(F, axis=1)
#calcul de la matrice Lc: la matrice centrée

Lc=np.linalg.inv(DK)@F-(acp_functions.matrix_of_one(np.shape(DK)[0])@np.transpose(L_barre))
Cc=np.linalg.inv(DL)@F-(acp_functions.matrix_of_one(np.shape(DL)[0])@np.transpose(C_barre))

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [ ]:
acp_functions.completed_pca(Lc,np.linalg.inv(DL),np.linalg.inv(DK))
acp_functions.completed_pca(Cc,np.linalg.inv(DK),np.linalg.inv(DL))

NameError: name 'acp_functions' is not defined